export const searchFeedbackQuery = `
  WITH query AS (
    SELECT SNOWFLAKE.CORTEX.EMBED_TEXT_768(
      'snowflake-arctic-embed-m-v1.5',
      ?
    ) AS qvec
  )
  SELECT 
    f.FEEDBACK_ID,
    f.COURSE_NAME,
    f.COURSE_ID,
    f.USERNAME,
    f.TEXT_RESPONSE,
    f.THEMES,
    f.ACTIONABLE_SUGGESTION,
    f.SENTIMENT_LABEL,
    f.INSTRUCTOR_NAME,
    f.INSTRUCTOR_ID,
    VECTOR_COSINE_SIMILARITY(f.RESPONSE_EMBEDDING, q.qvec) AS cosine_sim
  FROM FEEDBACK_DEMO.HACKATHON.MOODLE_FEEDBACK_AI_AUG f, query q
  ORDER BY cosine_sim DESC
  LIMIT 100
`;

export const cortexCompletionQuery = `
  SELECT SNOWFLAKE.CORTEX.COMPLETE(
    'llama3-8b',
    ?
  ) AS RESPONSE
`;

export const getSummaryQueryDataset = `
  SELECT
    COURSE_ID,
    NUMBER_OF_FEEDBACKS,
    NUMBER_OF_POSITIVE_FEEDBACK,
    NUMBER_OF_NEUTRAL_FEEDBACK,
    NUMBER_OF_NEGATIVE_FEEDBACK,
    NUMBER_OF_THEME_CONTENT,
    NUMBER_OF_THEME_PLATFORM,
    NUMBER_OF_THEME_INSTRUCTOR,
    NUMBER_OF_THEME_EXPERIENCE,
    NUMBER_OF_THEME_OTHER,
    NUMBER_OF_URGENCY_FLAG_TRUE,
    NUMBER_OF_URGENCY_FLAG_FALSE,
    NUMBER_OF_NUMERIC_RESPONSE_1,
    NUMBER_OF_NUMERIC_RESPONSE_2,
    NUMBER_OF_NUMERIC_RESPONSE_3,
    NUMBER_OF_NUMERIC_RESPONSE_4,
    NUMBER_OF_NUMERIC_RESPONSE_5
  FROM FEEDBACK_DEMO.HACKATHON.SUMMARY_QUERY_DATASET;
`;
