export const getFeedbackQuery = `
  SELECT
    FEEDBACK_ID,
    COURSE_ID,
    COURSE_NAME,
    USER_ID,
    USERNAME,
    INSTRUCTOR_ID,
    INSTRUCTOR_NAME,
    TEXT_RESPONSE,
    NUMERIC_RESPONSE,
    SENTIMENT_RAW,
    SENTIMENT_LABEL,
    SENTIMENT_SCORE_PERCENT,
    URGENCY_FLAG,
    THEMES,
    ACTIONABLE_SUGGESTION,
    PROCESSED_AT
  FROM FEEDBACK_DEMO.HACKATHON.MOODLE_FEEDBACK_AI_AUG
`;

export const getCourseQuery = `
  SELECT
    COURSE_ID,
    COURSE_NAME,
    OVERVIEW_FEEDBACK
  FROM FEEDBACK_DEMO.HACKATHON.MOODLE_FEEDBACK_AI_AUG_COURSE
`;

export const getActionableInsightsQuery = `
  SELECT
    COURSE_ID,
    COURSE_NAME,
    OVERVIEW_ACT_INS,
    NPS
  FROM FEEDBACK_DEMO.HACKATHON.MOODLE_FEEDBACK_AI_ACT_INS_COURSE
`;
